version: 0.2

run-as: Linux-user-name


        
phases:
  install:
    
    runtime-versions:
      java: corretto8
      
    commands:
      - echo install
   
  pre_build:
   
    commands:
      - echo prebuild
    
  build:
   
    commands:
      - mvn package
     
   
  post_build:
    
    commands:
      - echo post build
   

artifacts:
  files:
    - '**/*'
    - target/rest-api-todos-aws-0.0.1-SNAPSHOT.jar
     discard-paths: yes
  